name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag Name (e.g. v1.5.11)'
        required: false
        default: 'v1.5.11'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

permissions:
  contents: write

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.tag_name != '' && inputs.tag_name || startsWith(github.ref, 'refs/tags/') && github.ref_name || 'v1.5.11' }}
      prerelease: false
